add_lunch_combo optipop_hammerhead-eng
add_lunch_combo optipop_hammerhead-user
add_lunch_combo optipop_hammerhead-userdebug
add_lunch_combo optipop_shamu-eng
add_lunch_combo optipop_shamu-user
add_lunch_combo optipop_shamu-userdebug
